### ISSUE TITLE
Add end point to prime the engine

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-rest-api-specification#30]
First call looks slow as the engine primes to satisfy the request. Add end point to call the prime engine API. In addition to priming allows applications to display information the engine is priming and include in debug output/logs for reference.

**Comment by barrycaceres** [comment]
Looking into doing this..

**Comment by antaenc** [comment]
@barrycaceres any updates on adding prime please?

**Comment by barrycaceres** [comment]
This is on the road map and should probably get squeezed in by end of March -- its not hard -- just need to prioritize it.

**Comment by barrycaceres** [comment]
This will likely instead be a startup option to disable priming and be on by default as something we automatically do

**Comment by barrycaceres** [comment]
We implemented this by always priming the engine on startup in the API Server without an endpoint.  There is a `-skipEnginePriming` option to skip priming the option.
