### ISSUE TITLE
Add ability for user to specify path

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-rest-api-specification#60]
**Is your feature request related to a problem? Please describe.**
A customer may route the Senzing API server using path-based routing.
For instance: `https://my.example.com/api/heartbeat`

**Describe the solution you'd like**
To support this in the OpenAPI specification, the existing `servers:` section of the specification

https://github.com/Senzing/senzing-rest-api-specification/blob/f912e6b9187aec968d37c4d39590c82d93d15ec3/senzing-rest-api.yaml#L26-L36

 needs to be modified to allow a path.  Perhaps:

```yaml
  - url: '{protocol}://{host}:{port}/{path}'
```

**Comment by docktermj** [comment]
This relates to https://github.com/Senzing/senzing-api-server/issues/214

**Comment by barrycaceres** [comment]
This is provided in the version 2.5.0 release of the API server and REST API Specification.
