### ISSUE TITLE
Add support for AWS Cognito 

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-rest-api-specification#64]
**Is your feature request related to a problem? Please describe.**
In an AWS Cloudformation that uses Cognito for authentication, a mechanism is needed to authenticate.

**Comment by docktermj** [comment]
Example:

https://github.com/suwa-yuki/swagger-3.0-oauth-with-cognito

**Comment by jamietypovsky** [comment]
This is no longer needed.
